### ISSUE TITLE
ModuleNotFoundError: No module named 'pointnet2_ops'

### ISSUE THREAD

**Issue by 2311762665** [shanjiayao/PTT#11]
Hello author, why did I follow the tutorial you gave, but the following error still occurs: ModuleNotFoundError: No module named 'pointnet2_ops'.

**Comment by shanjiayao** [comment]
Hi! @2311762665 

This is because `pointnet2_ops` is not installed correctly, you can check if it contains a package named pointnet2_ops through `pip list`, if not, you can execute the following command:

```bash
pip install 'git+https://github.com/erikwijmans/Pointnet2_PyTorch.git#egg=pointnet2_ops&subdirectory=pointnet2_ops_lib'
```
