### ISSUE TITLE
How to visualize the points with attention scores?

### ISSUE THREAD

**Issue by freshwk** [shanjiayao/PTT#12]
Hi, i want to know how to visualize the points with attention scores as shown in Fig.9 in your paper?
![image](https://user-images.githubusercontent.com/42930372/170056383-7b6ed0f2-1bfb-4210-87d3-778a1f68a21f.png)

**Comment by shanjiayao** [comment]
For attention points and scores, we set the voting scores in the voting stage as attention scores. The higher the score, the more attention the corresponding points have been focused on. As shown in Fig. 9.
