### ISSUE TITLE
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.

### ISSUE THREAD

**Issue by abchears** [shanjiayao/PTT#14]
作者，您好，我在尝试按照redme文件训练ptt模型时，遇到了以下问题：

qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

Aborted (core dumped)

环境是python 3.8
ubutu16.04.6
1080tiGPU
cuda10.2

另外这是通过MobaXterm远程连接该服务器的，并没有可视化窗口，请问这个会对代码的运行有影响吗？
希望能够得知这个问题应该如何解决。
感谢您优秀的工作。

**Comment by shanjiayao** [comment]
嗨！感谢您对我们工作的关注！

关于Qt报错的问题，我猜测应该是mayavi可视化导致的。首先麻烦您确认您的代码版本是否与仓库最新版本保持一致。最新的版本解决了mayavi可视化导致的Qt报错的bug。或者您可以直接全局搜索mayavi，然后将所有类似`import mayavi`的语句都注释掉即可。

关于您说的，使用远程连接服务器，由于我们使用mayavi做可视化，目前我没有找到合适的解决方案解决mayavi远程显示的问题，所以远程服务器无法加载可视化界面，导致可视化只能在本地或者宿主机运行。除此之外，单纯的训练和测试都不会影响代码在远程服务器上的运行。（ps:如果有兴趣，可以试试mmdet3d里面的open3d可视化，效果也很棒）

总结来说，您需要保证，远程服务器的代码并没有使用mayavi的可视化操作，这个问题应该就可以解决了。

**Comment by abchears** [comment]
是的，我将可视化的代码注释掉之后便可以正常训练，也许问题就是没有图形环境导致mayavi的运行出错。
感谢您的解答。
