### ISSUE TITLE
How to train with multiple gpus？

### ISSUE THREAD

**Issue by freshwk** [shanjiayao/PTT#15]
I don't see the relevant parameters here.
![image](https://user-images.githubusercontent.com/42930372/176177160-0ec2abf1-6943-43b7-8d56-52417044b2d7.png)

**Comment by shanjiayao** [comment]
Hi! @freshwk

We use the argument '--launcher' to train the model with ddp, and you can create a script as following:  

```bash
#!/usr/bin/env bash
cd tools
python3 -m torch.distributed.launch --nproc_per_node=1 train_tracking.py --launcher pytorch
```

**Comment by freshwk** [comment]
> Hi! @freshwk
> 
> We use the argument '--launcher' to train the model with ddp, and you can create a script as following:
> 
> ```shell
> #!/usr/bin/env bash
> cd tools
> python3 -m torch.distributed.launch --nproc_per_node=1 train_tracking.py --launcher pytorch
> ```
hi, thanks for your reply! It doesn't work. The code seems to be blocked. I have 2 gpus in one device. I just want to use these two gpus to train.
![image](https://user-images.githubusercontent.com/42930372/176331837-1a7a6f5c-c725-41b5-917f-1a78a7058c6a.png)

**Comment by shanjiayao** [comment]
Hi! @freshwk 

The repo is updated for supporting training with ddp. And you can follow the commands in README to train with 2 GPUs.

**Comment by freshwk** [comment]
Thanks, @shanjiayao

**Comment by freshwk** [comment]
hi, @shanjiayao something weird happens! The used gpu memory  changes a lot during training. And the estimated training time is not reduced compared to when training with one gpu. Maybe somthing is wrong!
![image](https://user-images.githubusercontent.com/42930372/176475457-40e579fd-871e-473a-a831-d3c716dbeed4.png)
![image](https://user-images.githubusercontent.com/42930372/176475531-ed84f4fb-3991-4cd1-9bb4-4582dcec0c38.png)
![image](https://user-images.githubusercontent.com/42930372/176475638-34249a53-2b78-45c5-9b41-136b6097bd62.png)

**Comment by shanjiayao** [comment]
Could you please provide more infos such as your cfg file?

**Comment by freshwk** [comment]
@shanjiayao  In fact, i follow the cfg file you provided. Could I have your wechat if it's convenient for you, I want to talk with you about this question. My wechat number is: freshwk. Thank you!

**Comment by freshwk** [comment]
> Could you please provide more infos such as your cfg file?

That's my fault. Now it is ok. Thank you
