### ISSUE TITLE
Nuscenes dataset

### ISSUE THREAD

**Issue by abchears** [shanjiayao/PTT#17]
Hello author, thank you for your excellent work, I would like to know how to download the Nuscenes dataset? Is it enough to download the entire Trainval data set or the KeyFrame blobs part.

**Comment by shanjiayao** [comment]
Hi, sorry for my late reply.  ^-^

Regarding the nuScenes dataset, I think you'd better download all the data. In fact, it is not just using key frames, and you also could reffer to our code https://github.com/shanjiayao/PTT/blob/master/tools/cfgs/nuscenes_models/ptt.yaml#L7

**Comment by abchears** [comment]
Ok, thank you very much for your reply
