### ISSUE TITLE
Questions about performance on the NuScenes dataset

### ISSUE THREAD

**Issue by liulangwuyang** [shanjiayao/PTT#19]
Hi, why is the difference between the performance of the PTT model on the NuScenes dataset in the paper "Real-time 3D Single Object Tracking with Transformer" and the one on github so obvious?

**Comment by shanjiayao** [comment]
For nuScenes, we follow the settings of [BAT](https://github.com/Ghostish/Open3DSOT) to retrain and test our model. And these results are all trained with batchsize 48 on a single Nvidia RTX 3090, while the results of [extended journal paper](https://ieeexplore.ieee.org/document/9695195) are trained with 8 x 2080Ti GPUs.

**Comment by liulangwuyang** [comment]
Ok, thank you very much for your reply
