### ISSUE TITLE
Visualization tracking

### ISSUE THREAD

**Issue by freshwk** [shanjiayao/PTT#5]
Thank you for your open-source code. Could you please tell me how to visualize the tracking process?  I find you pass this stage in your code.
![image](https://user-images.githubusercontent.com/42930372/161198065-8536d42b-315e-49cf-8856-9d0a1b1600ba.png)

**Comment by shanjiayao** [comment]
Hi, thank you for your interest in our project! @freshwk 

In fact, here we want to keep more freedom for users, and we could provide a demo code for reference.

```python
from mayavi import mlab as mlab
from tools.visual_utils import visualize_utils as V
V.draw_scenes_tracking(
    points=self.ret_dict["this_PC"].points.transpose(),
    gt_boxes=self.ret_dict["this_BB"],
    ref_boxes=self.ret_dict["results_BBs"][-1],
    ref_scores=None, ref_labels=np.array('Car')
)
mlab.show(1)
input()
```

**Comment by freshwk** [comment]
> Hi, thank you for your interest in our project! @freshwk
> 
> In fact, here we want to keep more freedom for users, and we could provide a demo code for reference.
> 
> ```python
> from mayavi import mlab as mlab
> from tools.visual_utils import visualize_utils as V
> V.draw_scenes_tracking(
>     points=self.ret_dict["this_PC"].points.transpose(),
>     gt_boxes=self.ret_dict["this_BB"],
>     ref_boxes=self.ret_dict["results_BBs"][-1],
>     ref_scores=None, ref_labels=np.array('Car')
> )
> mlab.show(1)
> input()
> ```

ok. Thank you!
