### ISSUE TITLE
Question about Demo_tracking.py

### ISSUE THREAD

**Issue by xieyunjiao-holo** [shanjiayao/PTT#6]
Hi, I've been learning about your work recently. This interface appears when running demo_tracking.py, I'm not sure what to enter next? 
Can you provide the usage instructions for demo_tracking.py?
And what is the abbreviation for pts?

![image](https://user-images.githubusercontent.com/99383669/162868220-7709a60e-7d02-4378-a694-98b09673c1c9.png)

**Thank you for your response.**

**Comment by shanjiayao** [comment]
Hi, thank you for your interest in our project! @xieyunjiao-holo 

In fact, the demo_tracking.py is used to test the network structure and print the network parameters. To better debug, I used ipdb to add breakpoints. And you can press "c" then click enter to go to the next breakpoint. For more usage of ipdb, you can refer to https://hasil-sharma.github.io/2017-05-13-python-ipdb/

In addition, the pts is the abbreviation for points.
