### ISSUE TITLE
Model Reasoning Questions

### ISSUE THREAD

**Issue by xieyunjiao-holo** [shanjiayao/PTT#7]
嗨，打扰了。
你的算法在给每个序列做推理的时候，始终使用第一帧模板帧来推理整个序列吗？
还是每一帧的前一帧来作为模板帧？
调试的时候我怎样可以可视化出来模型推理一次的过程中具体是怎样运算的呢？
不知道为什么，我每次debug的断点处，batch_dict中显示已经计算出3D框了，我想搞清楚多目标跟踪，从何处入手呢？谢谢前辈指点^V^。

**Comment by shanjiayao** [comment]
Please ref to https://github.com/shanjiayao/PTT/blob/master/tools/cfgs/kitti_models/ptt.yaml#L149

![image](https://user-images.githubusercontent.com/37529041/163529559-3bae0c0f-ad2a-4506-bf24-4644686d9785.png)

The default option is first and previous.

**Comment by xieyunjiao-holo** [comment]
> The default option is first and previous.

这个的意思是，融合的是该序列当前预测帧的第一帧和其前一帧的真值框吗？
还是点云数据呢？
![image](https://user-images.githubusercontent.com/99383669/163532120-94c55e9b-35fb-4f6e-adfe-b6c66576b6e4.png)
是这里的代码吗？

**Comment by shanjiayao** [comment]
We concatenate the points by using the first and previous boxes. 

Maybe we can talk about this issue by using email. shajiayao97@gmail.com

**Comment by xieyunjiao-holo** [comment]
> We concatenate the points by using the first and previous boxes.
> 
> Maybe we can talk about this issue by using email. [shajiayao97@gmail.com](mailto:shajiayao97@gmail.com)

![image](https://user-images.githubusercontent.com/99383669/163533942-dd4337a1-d817-4925-b8ac-33e37f8a52e9.png)
联系不到你哇

**Comment by shanjiayao** [comment]
shanjiayao97@gmail.com
